### ISSUE TITLE
Does not build after fresh clone

### ISSUE THREAD

**Issue by Kazark** [fsprojects/Fix#14]
Hey, Reid. This project looks really cool, but I haven't been able to build it.

I did a fresh clone onto my Windows 7 box. When I ran `./build.bat`, I got:

```
FSC : error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core [C:\github\Fix\tests\Fix.Tests\Fix.Tests.fsproj]

     3>FSC : error FS0229: Error opening binary file 'C:\github\Fix\temp\bin\FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core [C:\github\Fix\tests\Fix.Tests\Fix.Tests.fsproj]

     3>FSC : error FS3160: Problem reading assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file 'C:\github\Fix\temp\bin\FSharp.Core.dll
       ': FSharp.Core.sigdata not found alongside FSharp.Core [C:\github\Fix\tests\Fix.Tests\Fix.Tests.fsproj]
```

Other info:
```
> msbuild /version
Microsoft (R) Build Engine version 4.0.30319.18408
[Microsoft .NET Framework, version 4.0.30319.18444]
Copyright (C) Microsoft Corporation. All rights reserved.
```

I have both VS 2010 and VS 2013 on my machine, though VS 2013 is my primary one and the one that is aliased for in my Powershell environment. (I was building this from Powershell.)

Let me know what other information you might need.

Is there a binary I can download instead?

**Comment by Krzysztof-Cieslak** [comment]
I think You need F# 4.0 installed on Your PC - https://www.microsoft.com/en-us/download/details.aspx?id=48179

**Comment by reidev275** [comment]
@Kazark did @Krzysztof-Cieslak 's suggestion resolve your issue?

**Comment by Kazark** [comment]
@reidev275 I didn't try it yet. I'm going to assume that he is correct though and leave it at that for now unless I discover otherwise. Thanks!
