### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by forki** [fsprojects/Fix#26]
Do you already have some docs?

**Comment by reidev275** [comment]
Largely just the readme. I'm working on some Getting Started type material though

**Comment by Krzysztof-Cieslak** [comment]
We should generate GitHub pages for project, like all other F# OSS projects.

**Comment by reidev275** [comment]
Agreed

**Comment by Krzysztof-Cieslak** [comment]
I've put some docs on http://fsprojects.github.io/Fix. Probably not perfect yet, but I feel it's good starting point.

**Comment by forki** [comment]
Cool. Thanks
