### ISSUE TITLE
warning on solution

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/Fix#27]
After a fresh clone and opening in VS2015 update 1 I get this warning:

Some of the properties associated with the solution could not be read.

Solution builds and tests OK, so this appears only to be an annoyance.

**Comment by reidev275** [comment]
@jackfoxy I have had similar issues as well.  Haven't pinpointed why VS2015 does that yet though.  Thanks for opening

**Comment by reidev275** [comment]
@jackfoxy Can you please retry to see if the change resolved your issue.  For me it had to do with spaces rather than tabs in the sln file

**Comment by jackfoxy** [comment]
@reidev275 yes, it is "fixed" (pun intended). Thanks.
